<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GitOptionDiffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('git_options')->insert([
            [
                'git_id' => 9,
                'git_option' => '-p',
                'description' => 'パッチを生成する（パッチの生成の項を参照）。これはデフォルトです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-s',
                'description' => 'diffの出力を抑止します。git showのようにデフォルトでパッチを表示するコマンドや、-patchの効果をキャンセルする場合に便利です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-U',
                'description' => '通常の3行ではなく、<n>行の文脈でdiffを生成する。これは --patch を意味する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--output=<file>',
                'description' => 'stdoutではなく、特定のファイルに出力する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--output-indicator-new=<char>',
                'description' => '生成されたパッチにおいて、新しい行、古い行、文脈を示すために使用する文字を指定します。通常、それぞれ +、-、 " " です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--output-indicator-old=<char>',
                'description' => '生成されたパッチにおいて、新しい行、古い行、文脈を示すために使用する文字を指定します。通常、それぞれ +、-、 " " です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--output-indicator-context=<char>',
                'description' => '生成されたパッチにおいて、新しい行、古い行、文脈を示すために使用する文字を指定します。通常、それぞれ +、-、 " " です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--raw',
                'description' => 'diffをrawフォーマットで生成する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--patch-with-raw',
                'description' => '-p --raw の同義語です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--indent-heuristic',
                'description' => 'パッチを読みやすくするために、diffハンクの境界をずらすヒューリスティックを有効にします。これはデフォルトです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-indent-heuristic',
                'description' => 'インデントヒューリスティックを無効化する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--minimal',
                'description' => '可能な限り小さな差分を出すために、余計な時間をかける。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--patience',
                'description' => '「patience diff」アルゴリズムでdiffを生成する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--histogram',
                'description' => '「ヒストグラム差分」アルゴリズムで差分を生成する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--anchored=<text>',
                'description' => 'anchored diff」アルゴリズムでdiffを生成します。このオプションは複数回指定することができます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--diff-algorithm={patience|minimal|histogram|myers}',
                'description' => 'diffのアルゴリズムを選択します。バリエーションはpatience|minimal|histogram|myersのいずれか',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--stat[=<width>[,<name-width>[,<count>]]]',
                'description' => 'diffstatを生成する。デフォルトでは、ファイル名部分に必要なだけのスペースが使われ、残りはグラフ部分に使われます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--compact-summary',
                'description' => 'diffstatで、ファイルの作成や削除（「new」または「gone」、オプションでシンボリックリンクの場合は「+l」）、モードの変更（「+x」または「-x」でそれぞれ実行ビットの追加または削除）などの拡張ヘッダー情報を凝縮して出力します。この情報は、ファイル名部分とグラフ部分の間に置かれます。これは --stat を意味します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--numstat',
                'description' => 'statと似ているが、追加・削除された行数を10進数で表示し、パス名を省略せずに表示することで、より機械に優しい表示を行う。バイナリファイルの場合、0 0 の代わりに 2 - を出力する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--shortstat',
                'description' => '変更されたファイルの総数、追加された行数、削除された行数を含む --stat 形式の最終行のみを出力する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-X[<param1,param2,…​>]',
                'description' => '各サブディレクトリの相対的な変更量の分布を出力する。dirstatの動作は、カンマ区切りのパラメータリストを渡すことでカスタマイズすることができます。デフォルトはdiff.dirstat設定変数によって制御されます',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--cumulative',
                'description' => '-dirstat=cumulativeの同義語です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--dirstat-by-file[=<param1,param2>…​]',
                'description' => 'dirstat=files,param1,param2...と同義です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--summary',
                'description' => '作成、リネーム、モード変更などの拡張ヘッダー情報を凝縮して出力します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--patch-with-stat',
                'description' => 'p --statの同義語です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-z',
                'description' => 'raw、--numstat、--name-only、--name-statusが指定された場合、パス名をつぶさず、出力フィールドのターミネーターとしてNULを使用します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--name-only',
                'description' => '変更されたファイル名のみを表示します。ファイル名は多くの場合 UTF-8 でエンコードされています。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--name-status',
                'description' => '変更されたファイルの名前と状態のみを表示する。name-onlyと同様に、ファイル名はUTF-8でエンコードされることが多い。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--submodule[=<format>]',
                'description' => 'サブモジュールの差分をどのように表示するかを指定します。-submodule=shortを指定すると、short形式が使われます。このフォーマットは、範囲の最初と最後のコミット名を表示するだけです。submoduleまたは-submodule=logを指定した場合は、log形式が使用されます。この形式では、git-submodule[1] summary のように範囲内のコミットを一覧表示します。submodule=diffを指定すると、diff形式が使われます。この形式では、コミット範囲内のサブモジュールの内容の変更点をインラインで差分表示します。デフォルトはdiff.submoduleで、configオプションが未設定の場合はshortフォーマットとなります。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--color[=<when>]',
                'description' => '色付きのdiffを表示します。-color（=<when>を含まない）は、-color=alwaysと同じです。<when>には、always、never、autoのいずれかを指定します。color.uiとcolor.diffの設定により変更可能です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-color',
                'description' => 'カラーデフをOFFにする。これは、コンフィギュレーション設定をオーバーライドするために使用できます。color=neverと同じです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--color-moved[=<mode>]',
                'description' => '移動されたコード行は、異なる色で表示されます。これはdiff.colorMovedの設定によって変更することができます。<mode>のデフォルトは、オプションが与えられていない場合はno、モードがないオプションが与えられている場合はzebraとなります。modeは以下のいずれかでなければなりません。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-color-moved',
                'description' => 'ムーブディテクトをオフにする。これは、コンフィギュレーション設定を上書きするために使用することができます。color-moved=noと同じです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-color-moved-ws',
                'description' => '移動検出を行う際に、空白を無視しないようにする。これは、コンフィギュレーション設定を上書きするために使用することができます。color-moved-ws=noと同じです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--word-diff[=<mode>]',
                'description' => '変更された単語を<mode>で区切り、単語の差分を表示する。デフォルトでは、単語は空白で区切られる。以下の --word-diff-regex を参照。<mode>のデフォルトはplainで、以下のいずれかでなければならない。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--word-diff-regex=<regex>',
                'description' => '<regex>を使用して、空白以外の文字列を単語とみなすのではなく、単語が何であるかを決定する。また、--word-diffがすでに有効になっている場合を除き、--word-diffも有効になる。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--color-words[=<regex>]',
                'description' => 'word-diff=colorに加え、（正規表現を指定した場合）--word-diff-regex=<regex>に相当する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-renames',
                'description' => '設定ファイルでリネーム検出をデフォルトで行っている場合でも、リネーム検出をオフにする。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--[no-]rename-empty',
                'description' => 'リネームソースとして空のブロブを使用するかどうか。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--check',
                'description' => '変更によってコンフリクトマーカーや空白のエラーが発生した場合に警告を表示します。何を空白のエラーとみなすかは、core.whitespaceの設定によって制御されます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ws-error-highlight=<kind>',
                'description' => 'diffのcontext、old、new行の空白のエラーを強調表示します。複数の値はカンマで区切られ、noneは前の値をリセットし、defaultはリストを新しいものにリセットし、allはold,new,contextの略語です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--full-index',
                'description' => 'パッチフォーマット出力を生成する際に、最初の一握りの文字ではなく、完全な画像前後のブロブオブジェクト名を「index」行に表示します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--binary',
                'description' => 'full-indexに加え、git-applyで適用可能なバイナリdiffを出力します。patchを暗示する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--abbrev[=<n>]',
                'description' => 'diff-raw形式の出力やdiff-treeのヘッダーラインに40バイトの16進数の完全なオブジェクト名を表示する代わりに、オブジェクトを一意に参照する',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-B[<n>][/<m>]',
                'description' => '完全な書き換えの変更を、削除と作成のペアに分割する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-M[<n>]',
                'description' => 'リネームを検出する。n を指定すると、類似度指数（ファイルのサイズに対する追加・削除の量）の閾値を指定します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-C[<n>]',
                'description' => '名前の変更だけでなく、コピーも検出する。find-copies-harderも参照。nを指定した場合は、-M<n>と同じ意味を持つ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--find-copies-harder',
                'description' => 'パフォーマンス上の理由から、デフォルトでは、-Cオプションは、コピーの元のファイルが同じチェンジセットで変更された場合にのみコピーを検出します。このフラグは、コピー元の候補として、変更されていないファイルを検査するようにします。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-D',
                'description' => 'ヘッダのみを表示し、preimage と /dev/null の差分を表示しないようにします。結果のパッチは patch や git apply で適用されることを意図していません。これは、変更後のテキストのレビューに集中したい人のためだけのものです。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-l<num>',
                'description' => 'Mおよび-Cオプションは、名前変更/コピーのサブセットを安価に検出する予備的なステップと、残りのすべてのペアリングされていない宛先と関連するすべてのソースを比較する完全なフォールバック部分を含みます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--diff-filter=[(A|C|D|M|R|T|U|X|B)…​[*]]',
                'description' => '追加（A）、コピー（C）、削除（D）、変更（M）、名前変更（R）、タイプ（通常ファイル、シンボリックリンク、サブモジュールなど）の変更（T）、マージ解除（U）、不明（X）、ペアリング解除（B）のファイルのみを選択します。フィルタ文字は、任意の組み合わせで使用することができます（なしも含む）。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-S<string>',
                'description' => 'ファイル内で指定した文字列の出現回数が変化する差分を探す（追加・削除など）。スクリプターの使用を意図しています。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-G<regex>',
                'description' => 'パッチテキストに <regex> に一致する追加/削除された行が含まれる差分を探します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--find-object=<object-id>',
                'description' => '指定したオブジェクトの出現回数を変更する差分を検索する。Sと似ているが、引数が異なるだけで、特定の文字列を検索するのではなく、特定のオブジェクトIDを検索するものである。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--pickaxe-all',
                'description' => 'Sまたは-Gが変更を見つけたとき、<string>の変更を含むファイルだけでなく、そのチェンジセット内のすべての変更を表示します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--pickaxe-regex',
                'description' => 'Sに与えられた<string>を拡張POSIX正規表現として扱い、マッチさせる。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-O<orderfile>',
                'description' => '出力に現れるファイルの順序を制御します。これは、diff.orderFile設定変数を上書きします。diff.orderFileをキャンセルするには、-O/dev/nullを使用します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--skip-to=<file>',
                'description' => '<file>という名前のファイルより前のファイルを出力から捨てたり(skip to)、出力の最後に移動させたり(rotate to)します。これらは主に git difftool コマンドを使用するために考案されたもので、それ以外ではあまり役に立たないかもしれません。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-R',
                'description' => '2つの入力を入れ替える。つまり、インデックスやディスク上のファイルからツリーの内容への違いを表示する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--relative[=<path>]',
                'description' => 'プロジェクトのサブディレクトリから実行する場合、このオプションでディレクトリ外の変更を除外し、そのディレクトリからの相対パス名を表示するように指示することができます。サブディレクトリにいないとき（裸のリポジトリなど）は、<path>を引数に与えることで、どのサブディレクトリからの相対出力を行うか指定することができます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-a',
                'description' => 'すべてのファイルをテキストとして扱います。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ignore-cr-at-eol',
                'description' => '比較の際、行末のキャリッジリターンを無視する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ignore-space-at-eol',
                'description' => 'EOL時の空白の変化は無視する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-b',
                'description' => '空白の量の変化を無視する。これは、行末の空白を無視し、それ以外の1文字以上の空白の連続をすべて同等と見なす。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-w',
                'description' => '行を比較する際に空白を無視する。これは、一方の行に空白があり、他方の行に空白がない場合でも、違いを無視する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ignore-blank-lines',
                'description' => '行がすべて空白の変更を無視します。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-I<regex>',
                'description' => 'すべての行が<regex>に一致する変更を無視します。このオプションは複数回指定することができる。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--inter-hunk-context=<lines>',
                'description' => 'diffハンク間のコンテキストを指定された行数まで表示し、それによって互いに近いハンクを融合させる。デフォルトはdiff.interHunkContextで、configオプションが未設定の場合は0です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-W',
                'description' => '各変更に対して、関数全体をコンテキスト行として表示します。関数名は、git diff がパッチハンクヘッダを作成するのと同じ方法で決定されます',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--exit-code',
                'description' => 'diff(1)と同じようなコードでプログラムが終了するようにする。つまり、違いがあった場合は1、違いがない場合は0で終了する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--quiet',
                'description' => 'プログラムの出力をすべて無効にする。exit-codeを暗示する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ext-diff',
                'description' => '外部diffヘルパーの実行を許可する。gitattributes[5]で外部diffドライバを設定した場合は、git-log[1]と一緒にこのオプションを使用する必要があります。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-ext-diff',
                'description' => '外部差分ドライバを許可しない。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--textconv',
                'description' => 'バイナリファイルを比較する際に、外部のテキスト変換フィルタを実行することを許可する（または許可しない）。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ignore-submodules[=<when>]',
                'description' => 'diff生成時にサブモジュールの変更を無視する。<when>には、"none"、"untracked"、"dirty"、"all "のいずれかを指定します（デフォルトです）。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--src-prefix=<prefix>',
                'description' => 'a/の代わりに、与えられたソースプレフィックスを表示する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--dst-prefix=<prefix>',
                'description' => 'b/の代わりに、与えられた宛先プレフィックスを表示する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--no-prefix',
                'description' => '送信元または送信先のプレフィックスは表示しないでください。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--line-prefix=<prefix>',
                'description' => '出力の各行に追加の接頭辞を前置する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '--ita-invisible-in-index',
                'description' => 'デフォルトでは、"git add -N "で追加されたエントリーは、"git diff "では既存の空ファイルとして、"git diff -cached "では新しいファイルとして表示されます。このオプションを指定すると、エントリーは「git diff」では新規ファイルとして表示され、「git diff -cached」では存在しないものとして表示されます。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '-O',
                'description' => 'マージされていないエントリーのdiff出力を省略し、"Unmerged "とだけ表示します。作業ツリーとインデックスを比較する場合にのみ使用可能です。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'git_id' => 9,
                'git_option' => '<path>…​',
                'description' => '<paths>パラメータを指定すると、指定したパスに限定してdiffを取得します（ディレクトリ名を指定すると、その下のすべてのファイルについてdiffを取得できます）。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
